In [7]:
# check a specific value in list
a = [1,2,3,4,5,6,7,8,9]
if "a" in a:
    print("yes")
else:
    print("no")

no

Negative slicing/indexing
used to access items from end of the list
. It is from roght to left. value -1.
right is greatar than left.

In [5]:
# NEGATIVE SLICING
c = [1,2,3,4,5,6,7,8,9]
print(c)
print(c[-5:-2])

[1, 2, 3, 4, 5, 6, 7, 8, 9]
[5, 6, 7]

In [12]:
# Quick Task
c= [6,"Red","G","Y","b"]
if "6"  in c:
    print("yes")
else :
    print("no")

no

In [18]:
# Range of list
# listname(start:stop:step)
# print(list(range(0,5,2)))
# list men index error nahe ata agr 5 sa bara number ho . refer tpo abpove problem.
# only in range and slicing
animals = ["cat", "camel", "dog","mouse","cow"]
print(animals[1:4:3])
print(animals[-3:-1])

['camel']
['dog', 'mouse']

In [23]:
from re import I
# LIST COMPREHENSION
# newlist = [expression for item in iterable if condition == True]
list = [i*i for i in range(45)]
print(list)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625, 676, 729, 784, 841, 900, 961, 1024, 1089, 1156, 1225, 1296, 1369, 1444, 1521, 1600, 1681, 1764, 1849, 1936]

In [28]:
list = [i+2 for i in range(20) if i%2==0]
print(list)
list = [i for i in range(2,21) if i%2==0]
print(list)
list = [i for i in range(50) if i%2!=0]
print(list)

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20]
[2, 4, 6, 8, 10, 12, 14, 16, 18, 20]
[1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49]

In [34]:
n= ["oleh", "Muhammad", "Allah", "Ahmed"]
nwith_o = [ i for i in n if ("o")]
print(nwith_o)

['oleh', 'Muhammad', 'Allah', 'Ahmed']

In [40]:
list= ["AHSAN", "ali"]
list[0] = "ahsan"
print(list)

['ahsan', 'ali']

In [ ]:
# TUPLE OPERATIONS
t1 = (2,3,4,5,3)

In [44]:
# taslk
t1 = (1,2,3,5,3)
t2 = (4,5,6,7)
for i in range (len(t1)):
    print(t1[i]+t2[i], end =" ")

5 7 9 12

IndexError: tuple index out of range

In [46]:
# tasks
# addition
t1 = (1,2,3,4,5)
t2 = (6,7,8,9,10)
print(t1+t2)
# subtraction
# print(t2-t1) not supported AS DO NOT SUPPORT ARITHMETIC OPERATIONS

(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)

TypeError: unsupported operand type(s) for -: 'tuple' and 'tuple'

In [56]:
ted = []
for i in range(5) :
  ted[i] = int(input("enter a number: "))
ted = tuple(ted)
print(ted)

enter a number: 1,2,3,4,5

ValueError: invalid literal for int() with base 10: '1,2,3,4,5'

In [63]:
ted1 = []
for i in range(2):
    ted1.append(int(input("enter a number for first tuple: ")))  # Append each number to the list after converting it to an integer.
ted1 = tuple(ted1)
print(ted)
ted2 = []
for i in range(2):
    ted22.append(int(input("enter a number for second tuple: ")))  # Append each number to the list after converting it to an integer.
ted2 = tuple(ted2)
print(ted)
print(ted1+ted2)

enter a number for first tuple: 1
enter a number for first tuple: 2
(2, 3, 4, 4, 3)

NameError: name 'ted22' is not defined

In [70]:
ted1 = []
for i in range(2):
    ted1.append(int(input("enter a number for first tuple: ")))  # Append each number to the list after converting it to an integer.
ted1 = tuple(ted1)
print(ted1)
ted2 = []
for i in range(2):
    ted2.append(int(input("enter a number for second tuple: ")))  # Append each number to the list after converting it to an integer.
ted2 = tuple(ted2)
print(ted2)
for i in range(len(ted1)):
    print(ted1[i]+ted2[i], end=" ")

enter a number for first tuple: 8
enter a number for first tuple: 8
(8, 8)
enter a number for second tuple: 8
enter a number for second tuple: 9
(8, 9)
16 17

In [38]:
84
5# TUPLE ARE IMMUTABLE
t1= (1,2,3,4,5)
t2 = (6,7,8,9,10)
print(t1,t2)
t3 = t1+t2
print(t3)

(1, 2, 3, 4, 5) (6, 7, 8, 9, 10)
(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)

In [71]:

ted1 = []
for i in range(2):
    ted1.append(int(input("enter a number for first tuple: ")))  # Append each number to the list after converting it to an integer.
ted1 = tuple(ted1)
print(ted1)
ted2 = []
for i in range(2):
    ted2.append(int(input("enter a number for second tuple: ")))  # Append each number to the list after converting it to an integer.
ted2 = tuple(ted2)
print(ted2)
ted1= tuple(ted1)
ted2= tuple(ted2)
for i in range(len(ted1)):
    print(ted1[i]-ted2[i], end=" ")

enter a number for first tuple: 3
enter a number for first tuple: 4
(3, 4)
enter a number for second tuple: 4
enter a number for second tuple: 3
(4, 3)
-1 1

In [76]:
# positive indexing
tod = [1,2,3,4,5,6,7,8,9]
print(tod[1:3])
# negative indexing
tod = [1,2,3,4,5,6,7,8,9]
print(tod[-3:-1])

[2, 3]
[7, 8]